#                                                            Developed by Senkex
#                                                        (Aquatic Studios @ (C) 2026)

name: AquaSpawn
version: '${version}'
author: 'Senkex'

api-version: '1.16'
folia-supported: true

main: com.aquaticstudios.aquaspawn.AquaSpawn
website: 'https://github.com/aquatic-studios'

commands:
  aquaspawn:
    description: Main command.
    aliases: [aqspawn]
  spawn:
    description: Teleport to the server spawn.